# Generated by Django 4.0.2 on 2022-05-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_follow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollow',
            old_name='followee',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='userfollow',
            old_name='follows',
            new_name='source',
        ),
    ]
