# Generated by Django 4.0.2 on 2022-05-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('naive_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFollowing', models.BooleanField(default=True)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='naive_user.user')),
                ('follows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='naive_user.user')),
            ],
        ),
    ]
